#! /bin/sh

echo '## Ensure directory clean for analysis ##'
rm -r /home/node/working/*

echo '## Copy project to working folder ##'
cp -r /home/node/project /home/node/working

cd /home/node/working/project

# setup for npm credentials
echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

npm install --unsafe-perm --no-optional
if [[ -z $VERSION ]]; then
  npm publish
else
  npm version ${VERSION}
  npm publish --tag next
fi

